/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.senac.projetobiblioteca;

/**
 *
 * @author vf983
 */
public class TelaCadastroLivros extends javax.swing.JDialog {
private Dados dados;
    /**
     * Creates new form TelaCadastroLivros
     */
    public TelaCadastroLivros(java.awt.Frame parent,Dados dados) {
        super(parent);
        this.dados = dados;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLnomeCadastroLivro = new javax.swing.JLabel();
        JLautorCadastroLivro = new javax.swing.JLabel();
        JLgeneroCadastroLivro = new javax.swing.JLabel();
        JTFnomeCadastroLivro = new javax.swing.JTextField();
        JTFautorCadastroLivro = new javax.swing.JTextField();
        JTFgeneroCadastroLivro = new javax.swing.JTextField();
        JBconfirmCadastroLivro = new javax.swing.JButton();
        JBconfirmVendaCadastroLivro = new javax.swing.JButton();
        JLpreçoCadastroLivro = new javax.swing.JLabel();
        JTFpreçoCadastroLivro = new javax.swing.JTextField();
        JBremoveLivro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLnomeCadastroLivro.setText("TÍTULO");

        JLautorCadastroLivro.setText("AUTOR");

        JLgeneroCadastroLivro.setText("GÊNERO");

        JBconfirmCadastroLivro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBconfirmCadastroLivro.setText("ALUGUEL");
        JBconfirmCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBconfirmCadastroLivroActionPerformed(evt);
            }
        });

        JBconfirmVendaCadastroLivro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBconfirmVendaCadastroLivro.setText("VENDA");
        JBconfirmVendaCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBconfirmVendaCadastroLivroActionPerformed(evt);
            }
        });

        JLpreçoCadastroLivro.setText("PREÇO");

        JBremoveLivro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBremoveLivro.setText("REMOVE");
        JBremoveLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBremoveLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLautorCadastroLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(129, 129, 129))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLnomeCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(283, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBconfirmCadastroLivro)
                                .addGap(32, 32, 32)
                                .addComponent(JBconfirmVendaCadastroLivro))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JLpreçoCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 48, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JLgeneroCadastroLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFgeneroCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFpreçoCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFautorCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFnomeCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)))
                        .addGap(27, 27, 27)
                        .addComponent(JBremoveLivro)
                        .addGap(0, 120, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLnomeCadastroLivro)
                    .addComponent(JTFnomeCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLautorCadastroLivro)
                    .addComponent(JTFautorCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLgeneroCadastroLivro)
                    .addComponent(JTFgeneroCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLpreçoCadastroLivro)
                    .addComponent(JTFpreçoCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBconfirmCadastroLivro)
                    .addComponent(JBconfirmVendaCadastroLivro)
                    .addComponent(JBremoveLivro))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBconfirmCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBconfirmCadastroLivroActionPerformed
         LivrosAluguel roger = new LivrosAluguel(
                 this.JTFnomeCadastroLivro.getText(),
                 this.JTFautorCadastroLivro.getText(),
                 this.JTFgeneroCadastroLivro.getText());
    this.dados.getBiblioteca().addLivroAluguel(roger);
    this.dispose();
    }//GEN-LAST:event_JBconfirmCadastroLivroActionPerformed

    private void JBconfirmVendaCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBconfirmVendaCadastroLivroActionPerformed
         LivrosVenda roger = new LivrosVenda(
                 this.JTFnomeCadastroLivro.getText(),
                 this.JTFautorCadastroLivro.getText(),
                 this.JTFgeneroCadastroLivro.getText(),
                 this.JTFpreçoCadastroLivro.getText());
    this.dados.getBiblioteca().addLivroVenda(roger);
    this.dispose();
    }//GEN-LAST:event_JBconfirmVendaCadastroLivroActionPerformed

    private void JBremoveLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBremoveLivroActionPerformed
         LivrosAluguel roger = new LivrosAluguel(
                 this.JTFnomeCadastroLivro.getText(),
                 this.JTFautorCadastroLivro.getText(),
                 this.JTFgeneroCadastroLivro.getText());
    this.dados.getBiblioteca().removeLivroAluguel(roger);
    this.dispose();
    }//GEN-LAST:event_JBremoveLivroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBconfirmCadastroLivro;
    private javax.swing.JButton JBconfirmVendaCadastroLivro;
    private javax.swing.JButton JBremoveLivro;
    private javax.swing.JLabel JLautorCadastroLivro;
    private javax.swing.JLabel JLgeneroCadastroLivro;
    private javax.swing.JLabel JLnomeCadastroLivro;
    private javax.swing.JLabel JLpreçoCadastroLivro;
    private javax.swing.JTextField JTFautorCadastroLivro;
    private javax.swing.JTextField JTFgeneroCadastroLivro;
    private javax.swing.JTextField JTFnomeCadastroLivro;
    private javax.swing.JTextField JTFpreçoCadastroLivro;
    // End of variables declaration//GEN-END:variables
}
