/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.senac.projetobiblioteca;

import br.com.senac.projetobiblioteca.Dados;
import br.com.senac.projetobiblioteca.BibliotecaPoggers;

/**
 *
 * @author vf983
 */
public class TelaCadastro extends javax.swing.JDialog {
   private Dados dados;

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro(java.awt.Frame parent,Dados dados) {
        super(parent);
        this.dados = dados;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLnomeCadastro = new javax.swing.JLabel();
        JTFnomeCadastro = new javax.swing.JTextField();
        JLcelularCadastro = new javax.swing.JLabel();
        JTFcelularCadastro = new javax.swing.JTextField();
        JLemailCadastro = new javax.swing.JLabel();
        JTFemailCadastro = new javax.swing.JTextField();
        JLsenhaCadastro = new javax.swing.JLabel();
        JTFsenhaCadastro = new javax.swing.JPasswordField();
        JLconfirmSenhaCadastro = new javax.swing.JLabel();
        JPFconfirmSenhaCadastro = new javax.swing.JPasswordField();
        JBconfirmaCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLnomeCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLnomeCadastro.setText("NOME COMPLETO:");

        JLcelularCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLcelularCadastro.setText("CELULAR:");

        JTFcelularCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcelularCadastroActionPerformed(evt);
            }
        });

        JLemailCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLemailCadastro.setText("E-MAIL:");

        JLsenhaCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLsenhaCadastro.setText("SENHA:");

        JTFsenhaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFsenhaCadastroActionPerformed(evt);
            }
        });

        JLconfirmSenhaCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLconfirmSenhaCadastro.setText("CONFIRMAR:");

        JBconfirmaCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JBconfirmaCadastro.setText("CONFIRMAR");
        JBconfirmaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBconfirmaCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFnomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLemailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLsenhaCadastro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFemailCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFsenhaCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLcelularCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTFcelularCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLnomeCadastro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JLconfirmSenhaCadastro)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JBconfirmaCadastro))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(JPFconfirmSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(12, 225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLnomeCadastro)
                    .addComponent(JTFnomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLcelularCadastro)
                    .addComponent(JTFcelularCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLemailCadastro)
                    .addComponent(JTFemailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLsenhaCadastro)
                    .addComponent(JTFsenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLconfirmSenhaCadastro)
                    .addComponent(JPFconfirmSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(JBconfirmaCadastro)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFcelularCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcelularCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFcelularCadastroActionPerformed

    private void JBconfirmaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBconfirmaCadastroActionPerformed
    Cliente roger = new Cliente(
            this.JTFnomeCadastro.getText(),
            this.JTFcelularCadastro.getText(),
            this.JTFemailCadastro.getText(),
            this.JTFsenhaCadastro.getText());
    
    this.dados.getBiblioteca().addCliente(roger);
    this.dispose();
    }//GEN-LAST:event_JBconfirmaCadastroActionPerformed

    private void JTFsenhaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFsenhaCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFsenhaCadastroActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBconfirmaCadastro;
    private javax.swing.JLabel JLcelularCadastro;
    private javax.swing.JLabel JLconfirmSenhaCadastro;
    private javax.swing.JLabel JLemailCadastro;
    private javax.swing.JLabel JLnomeCadastro;
    private javax.swing.JLabel JLsenhaCadastro;
    private javax.swing.JPasswordField JPFconfirmSenhaCadastro;
    private javax.swing.JTextField JTFcelularCadastro;
    private javax.swing.JTextField JTFemailCadastro;
    private javax.swing.JTextField JTFnomeCadastro;
    private javax.swing.JPasswordField JTFsenhaCadastro;
    // End of variables declaration//GEN-END:variables
}
