/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.projetobiblioteca;

/**
 *
 * @author vf983
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private Dados dados = new Dados();
    /** 
     * Creates new form POHADATELAPRINCIPAL
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLtitulo = new javax.swing.JLabel();
        JBaluguel = new javax.swing.JButton();
        JBcompra = new javax.swing.JButton();
        JBcadastrar = new javax.swing.JButton();
        JBerro = new javax.swing.JButton();
        JBclientes = new javax.swing.JButton();
        JBcadastrarLivro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLtitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        JLtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLtitulo.setText("Biblioteca");

        JBaluguel.setText("ALUGAR");
        JBaluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBaluguelActionPerformed(evt);
            }
        });

        JBcompra.setText("COMPRAR");
        JBcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcompraActionPerformed(evt);
            }
        });

        JBcadastrar.setText("CADASTRO");
        JBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcadastrarActionPerformed(evt);
            }
        });

        JBerro.setText("ERRO");
        JBerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBerroActionPerformed(evt);
            }
        });

        JBclientes.setText("CLIENTES");
        JBclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBclientesActionPerformed(evt);
            }
        });

        JBcadastrarLivro.setText("CADASTRAR LIVRO");
        JBcadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcadastrarLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(JLtitulo)
                    .addComponent(JBaluguel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBcompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(JBclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBcadastrar)
                        .addGap(6, 6, 6))
                    .addComponent(JBcadastrarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBerro)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(JLtitulo)
                .addGap(18, 18, 18)
                .addComponent(JBaluguel)
                .addGap(18, 18, 18)
                .addComponent(JBcompra)
                .addGap(12, 12, 12)
                .addComponent(JBcadastrarLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBcadastrar)
                    .addComponent(JBclientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(JBerro)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBaluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBaluguelActionPerformed
        TelaAluguel dialogAl = new TelaAluguel( this ,this.dados);
        dialogAl.setVisible(true);
    }//GEN-LAST:event_JBaluguelActionPerformed

    private void JBcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcompraActionPerformed
        TelaCompra dialogComp = new TelaCompra(this , this.dados);
        dialogComp.setVisible(true);   
    }//GEN-LAST:event_JBcompraActionPerformed

    private void JBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcadastrarActionPerformed
        TelaCadastro dialogCadastro = new TelaCadastro(this,this.dados);
        dialogCadastro.setVisible(true);

    }//GEN-LAST:event_JBcadastrarActionPerformed

    private void JBerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBerroActionPerformed
           telaErro dialogErro = new telaErro(this,true);
           dialogErro.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_JBerroActionPerformed

    private void JBclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBclientesActionPerformed
           TelaClientes dialogClientes = new TelaClientes(this, this.dados);
           dialogClientes.setVisible(true);
    }//GEN-LAST:event_JBclientesActionPerformed

    private void JBcadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcadastrarLivroActionPerformed
       TelaCadastroLivros dialogCadastroLivros = new TelaCadastroLivros(this,this. dados);
       dialogCadastroLivros.setVisible(true);
    }//GEN-LAST:event_JBcadastrarLivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBaluguel;
    private javax.swing.JButton JBcadastrar;
    private javax.swing.JButton JBcadastrarLivro;
    private javax.swing.JButton JBclientes;
    private javax.swing.JButton JBcompra;
    private javax.swing.JButton JBerro;
    private javax.swing.JLabel JLtitulo;
    // End of variables declaration//GEN-END:variables
}
